## Load in Numpy

In [2]:
import numpy as np

## The Basics 

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]] )
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get Shape
b.shape

(2, 3)

In [7]:
# Get type
a.dtype

dtype('int32')

In [8]:
# Get size 
a.itemsize
b.itemsize

8

In [9]:
# get total size
a.nbytes

12

### Accessing / Chaing specific elements, rows, columns etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# get a specific element [r, c]
a[1,5 ]

np.int64(13)

In [12]:
# get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# get a specific column
a[:,2]

array([ 3, 10])

In [14]:
# getting a lil more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [15]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d Example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# get specfic element (work outside in)
b[0,1,1]

np.int64(4)

In [21]:
# replace
b[:,1,:] = [[9,9],[8,8]]

## Initializing Different Types of Array

In [23]:
# all 0s matrix
np.zeros((2,3,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [25]:
# all 1st matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [27]:
# any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [30]:
# any other number(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [31]:
# random decimal number
np.random.rand(4,2)

array([[0.03275873, 0.44065958],
       [0.36481746, 0.21326717],
       [0.71325146, 0.27001796],
       [0.65051668, 0.43752886]])

In [32]:
# Random integer valuesb
np.random.randint(7,size=(3,3))

array([[2, 5, 0],
       [1, 0, 1],
       [1, 3, 3]], dtype=int32)

In [34]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]
