## Numpy array and basics 

In [3]:
import numpy as np

### creating array from list

In [5]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)


arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)


1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


## List vs numpy array

In [7]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1, 2, 3]) #element wise multplication
print("Numpy array multiplication ", np_array * 2) # 2 is called scalar

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ",time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ",time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Numpy array multiplication  [2 4 6]

 List operation time:  0.22591280937194824

 Numpy operation time:  0.019229412078857422


### creating array from scrach

In [12]:
zeros = np.zeros((3, 4))
print("zeros array: \n" , zeros)

ones = np.ones((2, 3))
print("ones array: \n" , ones)

full = np.full((2, 2), 7)
print("full array: \n" , full)

random = np.random.random((2, 3))
print("random array: \n" , random)

sequence = np.arange(0, 10, 1.5)
print("sequence array: \n" , sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.55356583 0.01878897 0.17553242]
 [0.47957962 0.28978219 0.09218495]]
sequence array: 
 [0.  1.5 3.  4.5 6.  7.5 9. ]


### Vector, Matrix and Tensor

In [13]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1,2,3],
                   [4, 5,6 ]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [19]:
arr = np.array([[1,2,3],
               [4,5,6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size) #number of elements
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### Array Reshaping

In [25]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("\nReshaped array ", reshaped)

# returns orginal array
flattened = reshaped.flatten()
print("\nFlattened array ", flattened)

# ravel(returns view, insted of copy)
raveled = reshaped.ravel()
print("\nRaveled array ", raveled)

# Transpose 
transpose = reshaped.T
print("\nTransposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
